### ISSUE TITLE
사용할 라이브러리를 결정사항

### ISSUE THREAD

**Issue by egoavara** [2021-1-dobest/ioFarm_Daily-report-chart#1]
확정 
- React
- React-Redux
- React-router

미확정
- Material-UI
- nivo
- csv
- Papa Parse
- Rechart
- xlsx-js

추가로 필요한 라이브러리 있으면 여기서 공유한 후에 추가해 주세요

**Comment by egoavara** [comment]
모든 라이브러리 사용 사항이 결정되면 이 이슈는 닫을 겁니다.

**Comment by Jaejin-Han** [comment]
js-xlsx 추가해야 합니다

**Comment by egoavara** [comment]
다른 팀원분들이 sheetjs 관련 자료를 보내줘서 검토한 결과 sheetjs가 가장 잘 맞는다고 생각됩니다.

- React
- React-Redux
- React-Router 
- Material-UI
- nivo
- sheetjs

로 사용할 라이브러리가 최종 결정되었습니다.

단 React-Router는 현재 프로젝트에서
SPA앱을 만들기 위해 로딩된 상태인데 결과물로 예상되는 페이지는 1개면 충분하기에 추후에 뺄지 말지 결정할 예정입니다.

뺄지 말지가 최종결정되면 이 이슈는 다시 닫힐 것입니다.

**Comment by egoavara** [comment]
추가로 심각한 문제 발견, 
nivo는 복합 차트를 지원하지 않습니다!(왜?!)
rechart로  차트 엔진을 변경합니다
